name: release

on:
  release:
    types: [published]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          ARCHIVE_NAME: tracker_${{ env.GITHUB_REF_NAME }}_x86_64.tar.gz
          ARCHIVE_TYPES: tar.gz
          MINIFY: "true"
          TOOLCHAIN_VERSION: stable
